name: KaRon Coleman Sr
favicon: null
layout_spectrum: 0.5701861009001732
typography_spectrum: 0.4274836073163897
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5306757190264761
  lightness: 0.100695128319785
  saturation: 0.6362726653460413
  rhythmicContrast: 0.8132784583140165
purpose: []
